### ISSUE TITLE
recursive mkdir wrong path translation

### ISSUE THREAD

**Issue by ole1986** [wankdanker/node-sftpjs#10]
While using the mkdir method to create folder recursively I noted that line 69 of sftp-wrapper.js causing the end of every join to be a "\" (due to its normalization I guess).

Example: 
```
client.mkdir('my/subfolder/dir', true, (err) => { if(err) reject(err); });
```

Result into:

```
my\
my\subfolder
my\subfolder\dir
```

and all the folders are being create in the same root instead of inside the parent

**Comment by ole1986** [comment]
A quick workaround is to:
```
token += '/';
p = p + token;
```

**Comment by wankdanker** [comment]
I can't recreate what I am hearing you say. Or maybe I don't understand correctly.

```js
var SFTP = require('sftpjs');
var sftp = SFTP();

sftp.on('ready', function () {
        sftp.mkdir('my/subfolder/dir', true, function (err, data) {
                console.log(err, data);
                sftp.end();
        });
}).on('error', function (err) {
        console.log(err);
}).connect({
        host : process.env.SFTP_HOST
        , user : process.env.SFTP_USER
        , password : process.env.SFTP_PASSWORD
});
```

In my tests, this creates:

```
/home/wankdanker/my/subfolder/dir
```

Using sftpjs@1.3.4

What platform is the SSH server running on the target host?

**Comment by ole1986** [comment]
Details:

**Client:**
Windows 10 with  vscode 1.17 but also 1.18
Using sftpjs@1.3.4

**Server:**
openssh-server 6.7p1
openssh-sftp-server: 6.7p1

on Debian 8.9

I actually dont thing it has something to do with server but with the join method located in the line already mentioned

**Comment by ole1986** [comment]
It also make sense to convert it to "my\subfolder\dir" as this is supposed to be the normal behavior according to [npm path, line 230](https://github.com/jinder/path/blob/master/path.js#L230)

**Comment by wankdanker** [comment]
>It also make sense to convert it to "my\subfolder\dir" as this is supposed to be the normal behavior according to npm path, line 230

I think that is just the normal behavior for win32 as there is a separate join function for posix which uses `/`. 

I'm thinking the correct thing might be to do is to change `token += '/';` to `token += path.sep;` where path is `path = require('path');`.

That way it will be the correct path separator for whichever platform is running sftpjs.

**Comment by ole1986** [comment]
Well but that does not solve the issue, as ssh is expecting "/".
Otherwise you get multiple folder in the same root instead of an ancestry

So how about the below to also normalize it?

```
p = p + token.replace(/\.\//g, '/').replace(/[\/]{2,}/g, '/').replace(/^\//, '');
```

**Comment by wankdanker** [comment]
Oh, OK. I see.

We could probably just use `join = require('path').posix.join;`. Then it would avoid the platform specific separator and force '/'.

**Comment by ole1986** [comment]
Will there be a hotfix shortly available?

**Comment by wankdanker** [comment]
sftpjs@1.3.5 is available on npm. Please reopen this issue if not fixed.

**Comment by ole1986** [comment]
Thank you - working!
