### ISSUE TITLE
No err on not existence file

### ISSUE THREAD

**Issue by rajashekhargundeti** [wankdanker/node-sftpjs#3]
hi,
I'm trying to pull a non exist file and catch the exception, but i failed to catch it. could you please let me know how i could do this. err placeholder in the call back function also not holding it. In fact, i'm getting a stream to a non-exist file in return to get method.

> try{
> ... client.get("/home/gundetir/app1.js", function(err, stream){ if (err ) throw err;
> ..... stream.pipe(require('fs').createWriteStream(new Date().getTime() + ""));
> ..... console.log("Get Done");
> ..... });
> ... }catch(e){
> ... console.log("Exception");
> ... }
> undefined
> Get Done
> Error: No such file
>     at SFTPStream._transform (C:\workspace\nodejs\client\node_modules\sftpjs\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:384:27)
>     at SFTPStream.Transform._read (_stream_transform.js:167:10)
>     at SFTPStream._read (C:\workspace\nodejs\client\node_modules\sftpjs\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:170:15)
>     at SFTPStream.Transform._write (_stream_transform.js:155:12)
>     at doWrite (_stream_writable.js:301:12)
>     at writeOrBuffer (_stream_writable.js:287:5)
>     at SFTPStream.Writable.write (_stream_writable.js:215:11)
>     at Channel.ondata (_stream_readable.js:536:20)
>     at emitOne (events.js:77:13)
>     at Channel.emit (events.js:169:7)

**Comment by wankdanker** [comment]
As soon as you get the stream object, can you attach an 'error' handler to it?

``` js
client.get("/home/gundetir/app1.js", function(err, stream)
    stream.on('error', function (err) {
        console.log('Error:' , err);
    });
    if (err ) throw err;
    stream.pipe(require('fs').createWriteStream(new Date().getTime() + ""));
    console.log("Get Done");
});
```

I tested this locally and that seemed to catch the error. However, I was receiving an 'Unhandled error event' error.

**Comment by rajashekhargundeti** [comment]
How would it create a stream for non-existence file?

**Comment by wankdanker** [comment]
I traced this back to the ssh2-streams module (createReadStream: https://github.com/mscdex/ssh2-streams/blob/master/lib/sftp.js#L2611; ReadStream: https://github.com/mscdex/ssh2-streams/blob/master/lib/sftp.js#L2611).

I haven't spent the time to completely understand the code, but it looks like it is creating a readable stream that has an `open()`method. The readable stream is returned from `createReadStream()` regardless of if the file exists. The `open()` method is called at some point on the readable stream and if there is any errors, they are emitted on the readable stream.

I might be able to work around this in this module by waiting for the `stream.on('open')` event before calling back with the stream.

**Comment by rajashekhargundeti** [comment]
post these changes, i'm unable to get the existing file as well.
